# Generated by Django 5.0 on 2025-11-11 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calificaciones', '0001_initial'),
        ('canchas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='cancha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canchas.cancha'),
        ),
    ]
