# Generated by Django 5.0 on 2025-11-11 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('puntaje', models.IntegerField()),
                ('comentario', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
