# Generated by Django 5.0 on 2025-11-10 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='cantidad_jugadores',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
