# Generated by Django 5.0 on 2025-11-11 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('canchas', '0001_initial'),
        ('recintos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancha',
            name='recinto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recintos.recinto'),
        ),
    ]
